# Build the self-hosted Lucide icon set used by the games (one icon family everywhere).
#   python tools/build_icons.py <path to lucide-static/icons>
# Copies each icon named below into images/icons/lucide/ (with Lucide's ISC licence) and writes
# js/lucide-icons.js: window.LUCIDE = {name: '<inner svg markup>'}. js/icons.js turns those into
# inline SVG (stroke = currentColor), so colour comes from CSS. Source: lucide-static 1.48.0 (npm).
import os, re, sys, json, shutil

NAMES = sorted(set('''
apple banana grape car bike bus flower flower-2 rose leaf clover sprout tree-pine sun cloud moon star heart
cat dog fish bird turtle book-open pencil key sailboat house tent umbrella music bell gift cake balloon guitar
piano palette drama rocket volleyball coffee pizza trophy paw-print
mail graduation-cap motorbike globe users smartphone sofa soup sunrise hourglass
brain search calculator text-search rainbow grid-3x3 shapes club spade circle-help list-ordered shuffle link
check-check flag scroll-text pen-line image blocks hash clock-3 tally-5 folder-tree type puzzle
upload camera play rotate-ccw eye lightbulb pointer party-popper sparkles timer circle-check check x delete
undo-2 arrow-left arrow-right book-open-text share-2 volume-2 volume-x a-large-small menu flame
chart-no-axes-column medal gamepad-2 calendar-days
circle square triangle diamond hexagon pentagon
crown dices bomb grid-2x2 film tv mic-vocal user-round tag dollar-sign map map-pin joystick orbit crosshair worm hammer
square-dashed layers gem layout-grid target brick-wall footprints spell-check-2 radio disc-3 car-front newspaper piggy-bank
pause square-play arrow-up arrow-down heart-crack lock key-round quote footprints
'''.split()))

def main(src):
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out_dir = os.path.join(root, 'images', 'icons', 'lucide')
    os.makedirs(out_dir, exist_ok=True)
    data = {}
    for n in NAMES:
        p = os.path.join(src, n + '.svg')
        s = open(p, encoding='utf8').read()
        shutil.copyfile(p, os.path.join(out_dir, n + '.svg'))
        inner = re.search(r'<svg[^>]*>(.*)</svg>', s, re.S).group(1)
        data[n] = re.sub(r'\s+', ' ', inner).replace(' />', '/>').strip()
    lic = os.path.join(os.path.dirname(src), 'LICENSE')
    shutil.copyfile(lic, os.path.join(out_dir, 'LICENSE'))
    js = ('// Lucide icons (https://lucide.dev), ISC licence: images/icons/lucide/LICENSE.\n'
          '// Generated by tools/build_icons.py from lucide-static 1.48.0. Do not edit by hand.\n'
          'window.LUCIDE=' + json.dumps(data, separators=(',', ':')) + ';\n')
    open(os.path.join(root, 'js', 'lucide-icons.js'), 'w', encoding='utf8', newline='\n').write(js)
    print(len(data), 'icons,', len(js) // 1024, 'KB')

if __name__ == '__main__':
    main(sys.argv[1])
